<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Registry</title>
</head>
<body>

<form method="post" action="/signIn">
    <label>Name:
        <input name="name" placeholder="Name">
    </label>
    <label>Password:
        <input name="password" type="password" placeholder="Password">
    </label>
    <input type="submit" value="Enter">
</form>


</body>
</html>